apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: udaconnect-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  replicas: 1
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      service: udaconnect-api
  template:
    metadata:
      labels:
        service: udaconnect-api
    spec:
      containers:
      - image: larien/nd064-udaconnect-api:latest
        name: udaconnect-api
        imagePullPolicy: Always
        env:
        - name: PERSONS_API_RETRIEVE_ALL
          valueFrom:
            configMapKeyRef:
              name: api-env
              key: PERSONS_API_RETRIEVE_ALL
        - name: LOCATIONS_API
          valueFrom:
            configMapKeyRef:
              name: api-env
              key: LOCATIONS_API
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
