apiVersion: v1
kind: Service
metadata:
  labels:
    service: locations-api
  name: locations-api
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30003
  selector:
    service: locations-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations-api
  name: locations-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations-api
  template:
    metadata:
      labels:
        service: locations-api
    spec:
      containers:
      - image: larien/locations-api:latest
        name: locations-api
        imagePullPolicy: Always
        env:
        - name: FLASK_RUN_PORT
          valueFrom:
            configMapKeyRef:
              name: api-env
              key: FLASK_RUN_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
