apiVersion: v1
kind: Service
metadata:
  labels:
    service: connections-api
  name: connections-api
spec:
  ports:
  - name: "5004"
    port: 5004
    targetPort: 5004
    nodePort: 30004
  selector:
    service: connections-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connections-api
  name: connections-api
spec:
  replicas: 1
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      service: connections-api
  template:
    metadata:
      labels:
        service: connections-api
    spec:
      containers:
      - image: larien/connections-api:latest
        name: connections-api
        imagePullPolicy: Always
        env:
        - name: PERSONS_API_RETRIEVE_ALL
          valueFrom:
            configMapKeyRef:
              name: api-env
              key: PERSONS_API_RETRIEVE_ALL
        - name: LOCATIONS_API
          valueFrom:
            configMapKeyRef:
              name: api-env
              key: LOCATIONS_API
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
